---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: debug-statements
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.3.5
    hooks:
      - id: python-typing-update
        stages: [manual]
        args: ["--py39-plus"]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--settings", "setup.cfg"]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        args: ["--pretty"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--config", "setup.cfg"]
